FROM node:12.19.1-alpine as builder

# Build-time variables:
ARG env=standalone

# Env vars for angular tests:
ENV CHROME_BIN=/usr/bin/chromium-browser \
	CHROME_PATH=/usr/lib/chromium/

COPY cyan_angular/ /app
COPY cyan_angular/src/karma.docker.conf.js /app/src/karma.conf.js

WORKDIR /app

RUN apk update && \
	apk add chromium

RUN rm -rf node_modules/ && \
	rm -rf dist/ && \
	npm install && \
	npm audit fix && \
	npm run build:$env && \
	npx ng test --sourceMap=false --browsers=Chrome_without_sandbox --watch=false

# Builds a small nginx image with static website
FROM nginx:alpine

ARG config=nginx.conf

RUN rm -rf /usr/share/nginx/html/*
RUN rm /etc/nginx/conf.d/default.conf
COPY ./cyan_nginx/$config /etc/nginx/conf.d
COPY --from=builder /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]