FROM mysql:latest

# NOTE: Any scripts, .sql files, etc. copied here will be run prior to mysql server startup.
COPY ./cyan_mysql/mysql-setup.sh /docker-entrypoint-initdb.d/mysql-setup.sh

RUN echo "lower_case_table_names=1" >> /etc/mysql/my.cnf

RUN chmod +x /docker-entrypoint-initdb.d/mysql-setup.sh