version: '2.1'
volumes:
  collected_static: {}
services:

  cyan-webserver:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_Webserver
    ports:
      - "80:80"
      # - "443:443"
    links:
      - cyan-api:uwsgi_flask

  cyan-api:
    build:
      context: .
      dockerfile: Dockerfile_API
    expose:
      - "5001"
    depends_on:
      - cyan-db
    volumes:
      - ./config/:/config
    environment:
      - DOCKER_HOSTNAME=${HOSTNAME}
      - MYSQL_ROOT_PASSWORD
    env_file:
      - ${CYAN_CONFIG:-./config/environments/local_docker_dev.env}
    links:
      - cyan-db

  cyan-db:
    build:
      context: .
      dockerfile: Dockerfile_Database
    volumes:
      - ${SQL_DUMP:-./cyan_mysql/no_dump.txt}:/tmp/dump.sql  # use optional dump file to build container DB
      - /var/www/app_data/cyano:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    env_file:
      - ${CYAN_CONFIG:-./config/environments/local_docker_dev.env}
      # - MYSQL_DATABASE=${DB_NAME}
      # - DB_NAME
      # NOTE: Below env vars create one-time pass displayed once in container stdout
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
      # - MYSQL_ONETIME_PASSWORD