# The builder from node image
FROM node:alpine as builder

# Build-time variables 
ARG env=stack
ARG config=nginx.conf

RUN apk update && apk add --no-cache make git

# Moves files into directory name "app"
WORKDIR /app
COPY cyan_angular/package.json cyan_angular/package-lock.json  /app/
RUN npm install @angular/cli -g
RUN cd /app && npm install
COPY cyan_angular/ /app

# Builds with $env variable
RUN cd /app && npm run build:$env

# Builds a small nginx image with static website
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
RUN rm /etc/nginx/conf.d/default.conf
COPY ./cyan_nginx/$config /etc/nginx/conf.d
COPY --from=builder /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]