"""compare_column

Revision ID: 7edb34e8429f
Revises: 16bbc0debcd6
Create Date: 2020-04-29 16:45:42.214897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7edb34e8429f"
down_revision = "16bbc0debcd6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("location", sa.Column("compare", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location", "compare")
    # ### end Alembic commands ###
