"""job_tables

Revision ID: 8be1c68ae581
Revises: be8127aa7edb
Create Date: 2021-03-05 08:38:11.890223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8be1c68ae581"
down_revision = "be8127aa7edb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_num", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=256), nullable=False),
        sa.Column("job_status", sa.String(length=32), nullable=False),
        sa.Column("input_file", sa.String(length=128), nullable=False),
        sa.Column("output_file", sa.String(length=128), nullable=False),
        sa.Column("num_locations", sa.Integer(), nullable=False),
        sa.Column("received_datetime", sa.DateTime(), nullable=False),
        sa.Column("started_datetime", sa.DateTime(), nullable=True),
        sa.Column("finished_datetime", sa.DateTime(), nullable=True),
        sa.Column("queue_time", sa.Integer(), nullable=True),
        sa.Column("exec_time", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job")
    # ### end Alembic commands ###
