# """empty message

# Revision ID: 970621e83c6c
# Revises: 8be1c68ae581
# Create Date: 2021-06-21 10:54:01.456453

# """
# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import mysql

# # revision identifiers, used by Alembic.
# revision = "970621e83c6c"
# down_revision = "8be1c68ae581"
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column("location", "type")
#     op.alter_column("user", "created", existing_type=mysql.DATETIME(), nullable=False)
#     op.alter_column(
#         "user", "last_visit", existing_type=mysql.DATETIME(), nullable=False
#     )
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column("user", "last_visit", existing_type=mysql.DATETIME(), nullable=True)
#     op.alter_column("user", "created", existing_type=mysql.DATETIME(), nullable=True)
#     op.add_column(
#         "location",
#         sa.Column(
#             "type",
#             mysql.SMALLINT(display_width=6),
#             server_default=sa.text("'1'"),
#             autoincrement=False,
#             nullable=False,
#         ),
#     )
#     # ### end Alembic commands ###
