"""reports table

Revision ID: a061d1f3c5c4
Revises: 8be1c68ae581
Create Date: 2021-11-30 20:51:51.712487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a061d1f3c5c4'
down_revision = '8be1c68ae581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_num', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=256), nullable=False),
    sa.Column('report_status', sa.String(length=32), nullable=False),
    sa.Column('report_date', sa.String(length=10), nullable=False),
    sa.Column('report_objectids', sa.Text(), nullable=True),
    sa.Column('report_tribes', sa.Text(), nullable=True),
    sa.Column('report_counties', sa.Text(), nullable=True),
    sa.Column('report_range_low', sa.Integer(), nullable=False),
    sa.Column('report_range_medium', sa.Integer(), nullable=False),
    sa.Column('report_range_high', sa.Integer(), nullable=False),
    sa.Column('received_datetime', sa.DateTime(), nullable=False),
    sa.Column('finished_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
