"""comments tables

Revision ID: c421782dd3e2
Revises: 351647c1b5a7
Create Date: 2020-06-15 14:26:50.598275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c421782dd3e2'
down_revision = '351647c1b5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('device', sa.String(length=64), server_default='N/A', nullable=False),
    sa.Column('browser', sa.String(length=64), server_default='N/A', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_body_id', sa.Integer(), nullable=False),
    sa.Column('comment_image', mysql.MEDIUMTEXT(), nullable=False),
    sa.ForeignKeyConstraint(['comment_body_id'], ['comment_body.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_images')
    op.drop_table('reply')
    op.drop_table('comment_body')
    op.drop_table('comment')
    # ### end Alembic commands ###
